### PR TITLE
Make `jetpack.move` work cross-device

### LINKED ISSUE #48: Can't cross device move file on windows platform.
I tried to use jetpack.move api to move file on windows platform, here is my code:
```js
import fs from 'fs-jetpack';

// ...
fs
.move(from, to)
.then(function (res) {
  // ...
}).catch(function(err) {
  // ...
});
```

```js
{
  Error: EXDEV: cross - device link not permitted,
  rename 'xxx/requestpipe.har' - > 'xxx/2cb5e04f-00f4-43b5-bf8e-a4d4decb7461.har'
  at Error(native) errno: -4037,
  code: 'EXDEV',
  syscall: 'rename',
  path: 'xxx/requestpipe.har',
  dest: 'xxx/2cb5e04f-00f4-43b5-bf8e-a4d4decb7461.har'
}
```

It's only worked on Mac machine. A bug?

### LINKED ISSUE #88: `move` does not work across partitions/devices
It throws `EXDEV` error.

I suggest using [move-file](https://github.com/sindresorhus/move-file) under the hood to solve this.

### PR DESCRIPTION
**Pull request by papb**
Closes #48 
Closes #88

The behavior I chose for when the destination already exists is the same currently happening when in the same device. See #92.

I did not add a test because I don't think it's possible to test for `EXDEV` in travis/appveyor. I tested manually though.

### CODE REVIEW

**Comment by szwacz** [comment]
Will you be interested in updating this PR after changes made by https://github.com/szwacz/fs-jetpack/pull/92 ? :)

**Comment by papb** [comment]
@szwacz Yes, will do as soon as possible, thank you!!

File: lib/move.js [hunk 1]
```diff
@@ -27,8 +29,25 @@ const moveSync = (from, to) => {
     fs.renameSync(from, to);
   } catch (err) {
     if (err.code !== "ENOENT") {
```
Comment (Richienb) [inline lib/move.js:31]: Instead of:

```js
if (err.code !== "ENOENT") {
	if (err.code === "EXDEV") {
		...1
	} else {
		...2
	}
} else {
	...3
}
```

we can refactor the code so that the if statements always use `===`:

```js
if (err.code === "ENOENT") {
	...3
} else if (err.code === "EXDEV") {
	...1
} else {
	...2
}
```

Comment (papb) [reply lib/move.js]: Thank you!! Done!

**Comment by papb** [comment]
@szwacz PR updated! :smile:

**Comment by szwacz** [comment]
The code looks good :)

There are some problems with node v14 on windows: https://ci.appveyor.com/project/szwacz/fs-jetpack/build/job/2gl5f46j3pm7akcl

I'd also need to test it on MacOS/Linux (I believe you're a Windows user so it was already tested there).

**Comment by papb** [comment]
@szwacz Would you like me to add a test by mocking `fs.rename` and `fs.renameSync` and making them throw `'EXDEV'`?

Also looks like Travis did not run, any idea why?

Also appveyor is not helpful with the Node 14 failure, unless I am missing something, it just says `Command exited with code -1073741819` with no log whatsoever... Do you have any idea why? Perhaps just re-running appveyor might fix it?

**Comment by szwacz** [comment]
I don't think this is good library to use mocks. After all the whole purpose of it is to change the state of file system, if you mock the file system then the most essential element was thrown away, and the remaining test tests very little. Tough luck, this part just won't be automatically tested.

Travis did run, just for some reason doesn't appear here: https://travis-ci.org/github/szwacz/fs-jetpack

Yes, the error with node 14 is wierd. Do you have this version installed on your windows machine and the tests pass?

**Comment by szwacz** [comment]
Ok, the AppVeyor error looks like their testing environment issue, and not issue of this library. Actually Travis is supporting now Windows builds: https://docs.travis-ci.com/user/multi-os/ I'll gieve it a try.

**Comment by szwacz** [comment]
I've tested it on MacOS, looks good, so released as v3.1.0

**Comment by papb** [comment]
Awesome, sorry for not replying earlier. Yes, works for me on windows :grin:
